substitutions:
  project_ver_let: v
  default_power_on_state: "Always On - Last Value"
  wifi_ap_timeout: 15s    # default to 15 second timeout for update bin file


packages:
  kauf_bulb_base: !include kauf-bulb.yaml


dashboard_import:
  package_import_url: github://KaufHA/kauf-rgbww-bulbs/kauf-bulb.yaml


esphome:
  name_add_mac_suffix: true


wifi:
  # add forced hash which isn't needed for dashboard import.
  # Allows saving wifi credentials across update.
  forced_hash: 2048874009

external_components:
  - source:
      type: local
      path: ./components


light:
  - id: !extend kauf_light
    #https://esphome.io/components/light/#light-effects
    effects:
      - flicker:
          alpha: 94%
          intensity: 12%
      - strobe:
      - pulse:
      - random:
      - candle:
          name: "Tealight - Calm Room"
          intensity: 10%
          # flicker_intensity: 05%
          flicker_probability: 50%
          flicker_transition_length: 100

      - candle:
          name: "Tealight - Breezy"
          intensity: 10%
          # flicker_intensity: 05%
          flicker_probability: 80%
          flicker_transition_length: 75

      - candle:
          name: "Candle - Calm"
          intensity: 10%

      - candle:
          name: "Candle Test Breezy 50ms"
          intensity: 15%
          # flicker_intensity: 10%
          flicker_transition_length: 50

      - candle:
          name: "Candle Test Breezy 75ms"
          intensity: 15%
          # flicker_intensity: 10%
          flicker_transition_length: 75
          colors:
              # 255, 128, 18
            - red: 100%
              green: 50%
              blue: 7%
            - red: 100%
              green: 40%
              blue: 0%

      - candle:
          name: "Candle Test Breezy v2 75ms"
          intensity: 15%
          # flicker_intensity: 10%
          flicker_transition_length: 75
          colors:
            - red: 100%
              green: 56%
              blue: 24%
            - red: 100%
              green: 50%
              blue: 0%

      - candle:
          name: "Candle Test Breezy 100ms"
          intensity: 15%
          # flicker_intensity: 10%
          flicker_transition_length: 100

      - candle:
          name: "Candle - Breezy 150ms"
          intensity: 15%
          # flicker_intensity: 10%
          flicker_transition_length: 150

      - candle:
          name: "Candle Test Breezy 200ms"
          intensity: 15%
          # flicker_intensity: 10%
          flicker_transition_length: 200

      - candle:
          name: "Candle Test Breezy 250ms"
          intensity: 15%
          # flicker_intensity: 10%
          flicker_transition_length: 250

      - fireplace:
          name: "Fireplace Test Breezy 15"
          intensity: 21%
          flicker_transition_length: 150
          colors:
            - red: 100%
              green: 50%
              blue: 0%
              # 255, 159, 64
            - red: 100%
              green: 56%
              blue: 24%

      - fireplace:
          name: "Fireplace Test Breezy 21"
          intensity: 21%
          flicker_transition_length: 200
          colors:
              # 255, 128, 0
            - red: 100%
              green: 50%
              blue: 0%
              # 255, 128, 18
            - red: 100%
              green: 50%
              blue: 7%
              # 255, 150, 20
            - red: 100%
              green: 58%
              blue: 8%
              # 255, 159, 64
            - red: 100%
              green: 66%
              blue: 22%
